Psychrometrics_Toolkit: Unit Compliance
BHoM/Psychrometrics_Toolkit pull request #55
Opened 2023-09-04 15:46 UTC by albinber

### NOTE: Depends on 

   
### Issues addressed by this PR

Closes #39

### Test files

### Changelog

### Additional comments

2023-09-04 15:47 UTC, albinber commented
@bhombot check compliance
@bhombot check call

2023-09-04 15:48 UTC, FraserGreenroyd requested changes
Please use the `typeof(Temperature)` quantity attributes available from `BH.oM.Quantity` [available here](https://github.com/BHoM/BHoM/tree/develop/Quantities_oM/Attributes), rather than putting the units in brackets in the input descriptions 😄

2023-09-04 15:48 UTC, FraserGreenroyd requested changes
Please also add `BHoM/Localisation_Toolkit` as a dependency in the `dependencies.txt` file 😄

2023-09-05 11:06 UTC, FraserGreenroyd requested changes
See initial comments - spaces after the `,` on attribute inputs across the board please - I did the first file then realised it's a pattern so putting back on @albinber and @Tom-Kingstone to resolve please 😄

2023-09-05 11:06 UTC, FraserGreenroyd commented on Psychrometrics_Engine/Compute/DensityWater.cs
> +        [Input("temperature", "Temperature.", typeof(Temperature))]
Replace `temperature` with `banana` and...
![image](https://github.com/BHoM/Psychrometrics_Toolkit/assets/18049174/006bf0ff-64e4-47ee-a6fd-5d9bcaa50e59)

What should the temperature be of? Is there something extra we can provide the user to help them with this input?

2023-09-05 11:06 UTC, FraserGreenroyd commented on Psychrometrics_Engine/Compute/FromHumidityRatio.cs
> +        [Input("dryBulbTemperature", "Dry-bulb temperature.",typeof(Temperature))]
```suggestion
        [Input("dryBulbTemperature", "Dry-bulb temperature.", typeof(Temperature))]
```

2023-09-05 11:06 UTC, FraserGreenroyd commented on Psychrometrics_Engine/Compute/FromHumidityRatio.cs
> +        [Input("humidityRatio", "Humidity ratio (kg_water/kg_dryair).",typeof(Ratio))]
```suggestion
        [Input("humidityRatio", "Humidity ratio (kg_water/kg_dryair).", typeof(Ratio))]
```

2023-09-05 11:06 UTC, FraserGreenroyd commented on Psychrometrics_Engine/Compute/FromHumidityRatio.cs
> +        [Input("pressure", "Air pressure, defaults to sea level air pressure (101,325).",typeof(Pressure))]
```suggestion
        [Input("pressure", "Air pressure, defaults to sea level air pressure (101,325).", typeof(Pressure))]
```

2023-09-05 11:06 UTC, FraserGreenroyd commented on Psychrometrics_Engine/Compute/FromHumidityRatio.cs
> +        [MultiOutput(0, "density", "Density.",typeof(Density))]
```suggestion
        [MultiOutput(0, "density", "Density.", typeof(Density))]
```

2023-09-05 11:06 UTC, FraserGreenroyd commented on Psychrometrics_Engine/Compute/FromHumidityRatio.cs
> +        [MultiOutput(1, "enthalpy", "Enthalpy.",typeof(SpecificEnergy))]
```suggestion
        [MultiOutput(1, "enthalpy", "Enthalpy.", typeof(SpecificEnergy))]
```

2023-09-05 11:06 UTC, FraserGreenroyd commented on Psychrometrics_Engine/Compute/FromHumidityRatio.cs
> +        [MultiOutput(1, "enthalpy", "Enthalpy.",typeof(SpecificEnergy))]
Banana again - what is `enthalpy`?

2023-09-05 11:06 UTC, FraserGreenroyd commented on Psychrometrics_Engine/Compute/FromHumidityRatio.cs
> +        [MultiOutput(2, "dewPoint", "Dew-point temperature.",typeof(Temperature))]
```suggestion
        [MultiOutput(2, "dewPoint", "Dew-point temperature.", typeof(Temperature))]
```

2023-09-05 11:06 UTC, FraserGreenroyd commented on Psychrometrics_Engine/Compute/FromHumidityRatio.cs
> +        [MultiOutput(4, "specificVolume", "Specific Volume.",typeof(VolumePerQuantity))]
```suggestion
        [MultiOutput(4, "specificVolume", "Specific Volume.", typeof(VolumePerQuantity))]
```

2023-09-05 11:06 UTC, FraserGreenroyd commented on Psychrometrics_Engine/Compute/FromHumidityRatio.cs
> +        [MultiOutput(5, "wetBulbTemperature", "Wet-bulb temperature.",typeof(Temperature))]
```suggestion
        [MultiOutput(5, "wetBulbTemperature", "Wet-bulb temperature.", typeof(Temperature))]
```

2023-09-05 14:13 UTC, FraserGreenroyd requested changes

2023-09-05 14:13 UTC, FraserGreenroyd commented on Psychrometrics_Engine/Compute/SaturatedVapourPressureWater.cs
> +        [Input("temperature", "Temperature.", typeof(Temperature))]
More bananas?

2023-09-05 14:13 UTC, FraserGreenroyd commented on Psychrometrics_Engine/Compute/SpecificHeatCapacityWater.cs
> +        [Input("temperature", "Temperature.", typeof(Temperature))]
More bananas?

2023-09-05 14:13 UTC, FraserGreenroyd commented on Psychrometrics_Engine/Compute/TemperatureAtAltitude.cs
> +        [Input("altitude", "Altitude.", typeof(Length))]
More bananas?

2023-09-05 14:13 UTC, FraserGreenroyd commented on Psychrometrics_Engine/Compute/TemperatureAtAltitude.cs
> +        [Output("temperature", "Temperature.", typeof(Temperature))]
More bananas?

2023-09-05 18:05 UTC, FraserGreenroyd requested changes

2023-09-05 18:05 UTC, FraserGreenroyd commented on Psychrometrics_Engine/Compute/DensityWater.cs
> +        [Input("water temperature", "Water Temperature.", typeof(Temperature))]
```suggestion
        [Input("temperature", "Water Temperature.", typeof(Temperature))]
```

2023-09-05 18:05 UTC, FraserGreenroyd commented on Psychrometrics_Engine/Compute/SaturatedVapourPressureWater.cs
> +        [Input("water temperature", "Water Temperature.", typeof(Temperature))]
```suggestion
        [Input("temperature", "Water Temperature.", typeof(Temperature))]
```

2023-09-05 18:05 UTC, FraserGreenroyd commented on Psychrometrics_Engine/Compute/SpecificHeatCapacityWater.cs
> +        [Input("water temperature", "Water Temperature.", typeof(Temperature))]
```suggestion
        [Input("temperature", "Water Temperature.", typeof(Temperature))]
```

2023-09-05 18:05 UTC, FraserGreenroyd commented on Psychrometrics_Engine/Compute/TemperatureAtAltitude.cs
> +        [Input("altitude above sea level", "Altitude above sea level.", typeof(Length))]
```suggestion
        [Input("altitude", "Altitude above sea level.", typeof(Length))]
```

2023-09-05 18:06 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2023-09-05 19:59 UTC, FraserGreenroyd commented
@BHoMBot check core
@BHoMBot check null-handling

2023-09-05 21:13 UTC, FraserGreenroyd commented
@BHoMBot check core
@BHoMBot check serialisation
@BHoMBot check versioning
@BHoMBot check installer

2023-09-06 08:33 UTC, FraserGreenroyd requested changes

2023-09-06 08:33 UTC, FraserGreenroyd commented on dependencies.txt
> +BHoM/Quantities_oM
```suggestion
BHoM/Localisation_Toolkit
```

2023-09-06 08:33 UTC, FraserGreenroyd commented
@BHoMBot check core

2023-09-06 09:23 UTC, FraserGreenroyd commented
@BHoMBot check core

2023-09-06 09:25 UTC, FraserGreenroyd requested changes

2023-09-06 09:25 UTC, FraserGreenroyd commented on dependencies.txt
> +BHoM/Units_Engine
```suggestion
```

2023-09-06 09:25 UTC, FraserGreenroyd commented
@BHoMBot check core

2023-09-06 09:27 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2023-09-06 09:27 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2023-09-06 11:21 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2023-09-06 13:32 UTC, FraserGreenroyd approved these changes
This is looking good now, great work @Tom-Kingstone and @albinber , great bit of pair programming between you both on this 😄

2023-09-06 14:06 UTC, FraserGreenroyd commented
@BHoMBot check ready-to-merge

2023-09-06 16:07 UTC, FraserGreenroyd commented
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: core, installer, null-handling, serialisation, versioning, ready-to-merge

2023-09-06 16:07 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2023-09-06 16:08 UTC, merged